_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": train_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 50
                - 51
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 50
                - 51
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.0
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
config:
    value: '{''model'': {''name'': ''SimpleModel'', ''learning_rate'': 0.001, ''batch_size'': 16}, ''trainer'': {''epochs'': 10, ''log_interval'': 10, ''save_interval'': 1, ''wandb_project'': ''dtu_mlops''}, ''data'': {''model_name'': ''distilbert-base-uncased'', ''data_path'': ''data/processed'', ''train_size'': 3000, ''data_seed'': 42, ''batch_size'': 32, ''test_ratio'': 0.2, ''val_ratio'': 0.2}}'
input_dim:
    value: 768
